name: Sincronizar con GitLab

on: [push, delete]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar remote de GitLab
        env:
          GL_TOKEN: ${{ secrets.GL_TOKEN }}
        run: |
          git remote add gitlab "https://oauth2:${GL_TOKEN}@gitlab.com/686f6c61-gr/github/${GITHUB_REPOSITORY#*/}.git"
          git push --mirror gitlab